theme: minima
title: parity check
description: a blog on software engineering and other random bits 
show_excerpts: true

header_pages:
  - about.md

minima:
  social_links:
    twitter: _y0ungk
    linkedin: young4k
    